import React, { useEffect, useMemo, useState } from 'react';
import { Activity, AlertTriangle, CalendarDays, CheckCircle2, Dumbbell, Library, Plus, RotateCcw, Save, Search, Trash2 } from 'lucide-react';

const STORAGE_KEY = 'rehab_strength_tracker_v2_draft';
const recommendedPlans = {
  1: { title: 'Lower A', type: 'Lower A', exercises: ['Hip Thrust','Dumbbell Romanian Deadlift','Seated Hamstring Curl','Leg Press','Hip Abductor Machine','Hip Adductor Machine','Pallof Press','Seated Heel Raise Partial Range'] },
  2: { title: 'Upper A', type: 'Upper A', exercises: ['Chest-Supported Dumbbell Row','Seated Cable Row — Neutral Grip','Wide-Neutral Lat Pulldown','Machine Chest Press','Face Pull','Rear Delt Fly','Hammer Curl'] },
  3: { title: 'Rehab + Cardio', type: 'Rehab + Cardio', exercises: ['Dog Walk','Seated Ankle Alphabet','Band Ankle Eversion','Band Ankle Inversion','Supported Single-Leg Balance','Bird Dog','Side Plank From Knees'] },
  4: { title: 'Lower B', type: 'Lower B', exercises: ['Leg Press','Glute Bridge Machine','Leg Extension','Seated Hamstring Curl','Cable Pull-Through','Hip Abductor Machine','Dead Bug'] },
  5: { title: 'Upper B', type: 'Upper B', exercises: ['Landmine Press','One-Arm Cable Row','Machine Chest Press','Wide-Neutral Lat Pulldown','Cable Lateral Raise','Rope Triceps Pressdown','Hammer Curl','Farmer Carry'] },
};
function todayIso(){return new Date().toISOString().slice(0,10)}
function num(v,f=0){const n=Number(v); return Number.isFinite(n)?n:f}
function defaultSet(i=1){return {setNumber:i,weight:'',weightUnit:'kg',reps:'',rpe:'',completed:true,notes:''}}
function makeExerciseFromLibrary(exercise, source='Added'){
  const targetSets = exercise.defaultSets || 3;
  return { localId: crypto?.randomUUID ? crypto.randomUUID() : String(Date.now()+Math.random()), exerciseId: exercise.id, name: exercise.exercise, source, category: exercise.category, status: exercise.status, coachNote: exercise.coachNote, targetSets, targetReps: exercise.defaultReps || '', backDuringExercise:'', nerveDuringExercise:'', ankleDuringExercise:'', shoulderDuringExercise:'', notes:'', sets: Array.from({length: Math.max(1,num(targetSets,3))},(_,i)=>defaultSet(i+1)) };
}
function Field({label,value,setValue,type='number',min=0,max=10}){return <label className="field"><span>{label}</span><input type={type} min={min} max={max} value={value} onChange={e=>setValue(e.target.value)} /></label>}
function Slider({label,value,setValue,lowGood=true}){return <label className="slider"><div className="row"><span>{label}</span><b>{value}</b></div><input type="range" min="0" max="10" value={value} onChange={e=>setValue(Number(e.target.value))}/><div className="rangeLabels"><span>{lowGood?'low':'poor'}</span><span>{lowGood?'high':'great'}</span></div></label>}
export default function App(){
  const [tab,setTab]=useState('today'); const [exercises,setExercises]=useState([]); const [exerciseStatus,setExerciseStatus]=useState('Loading exercise library…'); const [saveStatus,setSaveStatus]=useState(''); const [query,setQuery]=useState(''); const [categoryFilter,setCategoryFilter]=useState('All'); const [selectedPlan,setSelectedPlan]=useState('1');
  const [date,setDate]=useState(todayIso()); const [type,setType]=useState('Lower A'); const [workoutSource,setWorkoutSource]=useState('Recommended');
  const [sleep,setSleep]=useState(6); const [energy,setEnergy]=useState(6); const [stress,setStress]=useState(4); const [backPain,setBackPain]=useState(0); const [nerve,setNerve]=useState(0); const [anklePain,setAnklePain]=useState(0); const [ankleStability,setAnkleStability]=useState(5); const [shoulder,setShoulder]=useState(0); const [dogWalk,setDogWalk]=useState(30); const [notes,setNotes]=useState(''); const [workoutExercises,setWorkoutExercises]=useState([]);
  const [custom,setCustom]=useState({exercise:'',category:'Custom',equipment:'',movementPattern:'',primaryMuscles:'',status:'Custom',riskFlags:'',defaultSets:3,defaultReps:'10',defaultRpe:6,coachNote:''});
  useEffect(()=>{try{const raw=localStorage.getItem(STORAGE_KEY); if(raw){const d=JSON.parse(raw); setDate(d.date||todayIso()); setType(d.type||'Lower A'); setWorkoutSource(d.workoutSource||'Recommended'); setSleep(d.sleep??6); setEnergy(d.energy??6); setStress(d.stress??4); setBackPain(d.backPain??0); setNerve(d.nerve??0); setAnklePain(d.anklePain??0); setAnkleStability(d.ankleStability??5); setShoulder(d.shoulder??0); setDogWalk(d.dogWalk??30); setNotes(d.notes||''); setWorkoutExercises(d.exercises||[]);}}catch{} loadExercises();},[]);
  useEffect(()=>{localStorage.setItem(STORAGE_KEY,JSON.stringify({date,type,workoutSource,sleep,energy,stress,backPain,nerve,anklePain,ankleStability,shoulder,dogWalk,notes,exercises:workoutExercises}))},[date,type,workoutSource,sleep,energy,stress,backPain,nerve,anklePain,ankleStability,shoulder,dogWalk,notes,workoutExercises]);
  const readiness=useMemo(()=>{let s=25; s-=Math.max(0,7-sleep)*1.4; s-=Math.max(0,7-energy)*1.2; s-=stress*.7; s-=backPain*1.2; s-=nerve*1.8; s-=anklePain*1.3; s-=Math.max(0,7-ankleStability)*1.1; s-=shoulder*1.1; return Math.round(Math.max(0,Math.min(25,s)))},[sleep,energy,stress,backPain,nerve,anklePain,ankleStability,shoulder]);
  const coachNote=useMemo(()=>{if(nerve>=5||backPain>=6)return'Red flag day: rehab/cardio only. Avoid loaded hinge, leg press intensity and heavy spinal loading.'; if(anklePain>=5||ankleStability<=3)return'Ankle caution: keep exercises planted and controlled. Avoid calf raises, lunges, step-ups, running and jumping.'; if(shoulder>=5)return'Shoulder caution: avoid pulldowns, pressing, lateral raises and overhead work today.'; if(readiness<12)return'Red day: save readiness only or do rehab/cardio.'; if(readiness<18)return'Amber day: reduce load 10–20% and avoid new exercises.'; return'Green day: train as planned, 2–3 reps in reserve.'},[readiness,nerve,backPain,anklePain,ankleStability,shoulder]);
  const categories=useMemo(()=>['All',...Array.from(new Set(exercises.map(e=>e.category).filter(Boolean))).sort()],[exercises]);
  const filtered=useMemo(()=>{const q=query.toLowerCase().trim(); return exercises.filter(e=>(!q||[e.exercise,e.category,e.status,e.coachNote,(e.riskFlags||[]).join(' ')].join(' ').toLowerCase().includes(q))&&(categoryFilter==='All'||e.category===categoryFilter))},[exercises,query,categoryFilter]);
  async function loadExercises(){setExerciseStatus('Loading exercise library…'); try{const res=await fetch('/api/exercises'); const result=await res.json(); if(!res.ok)throw new Error(result.error||'Could not load exercises'); setExercises(result.exercises||[]); setExerciseStatus(`${result.exercises?.length||0} exercises loaded from Notion.`)}catch(e){setExerciseStatus(`Could not load exercise library: ${e.message}`)}}
  function applyRecommendedPlan(k){const plan=recommendedPlans[k]; setSelectedPlan(k); setType(plan.type); setWorkoutSource('Recommended'); setWorkoutExercises(plan.exercises.map(n=>exercises.find(e=>e.exercise===n)).filter(Boolean).map(e=>makeExerciseFromLibrary(e,'Recommended'))); setTab('workout')}
  function buildCustomWorkout(){setType('Custom Workout'); setWorkoutSource('Custom'); setWorkoutExercises([]); setTab('workout')}
  function addExercise(exercise, source='Added'){setWorkoutSource(workoutSource==='Recommended'?'Modified Recommended':workoutSource); setWorkoutExercises(p=>[...p,makeExerciseFromLibrary(exercise,source)]); setTab('workout')}
  async function createCustomExercise(){if(!custom.exercise.trim()){setExerciseStatus('Enter an exercise name first.'); return} setExerciseStatus('Creating custom exercise in Notion…'); try{const res=await fetch('/api/exercises',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({...custom,isCustom:true,active:true})}); const result=await res.json(); if(!res.ok)throw new Error(result.error||'Could not create exercise'); await loadExercises(); setExerciseStatus(`Created ${result.exercise}.`); setCustom({exercise:'',category:'Custom',equipment:'',movementPattern:'',primaryMuscles:'',status:'Custom',riskFlags:'',defaultSets:3,defaultReps:'10',defaultRpe:6,coachNote:''})}catch(e){setExerciseStatus(`Create failed: ${e.message}`)}}
  function updateExercise(id,patch){setWorkoutExercises(p=>p.map(ex=>ex.localId===id?{...ex,...patch}:ex))} function updateSet(id,i,patch){setWorkoutExercises(p=>p.map(ex=>ex.localId!==id?ex:{...ex,sets:ex.sets.map((s,j)=>j===i?{...s,...patch}:s)}))} function addSet(id){setWorkoutExercises(p=>p.map(ex=>ex.localId===id?{...ex,sets:[...ex.sets,defaultSet(ex.sets.length+1)]}:ex))} function removeExercise(id){setWorkoutExercises(p=>p.filter(ex=>ex.localId!==id))}
  async function saveWorkout(readinessOnly=false){const payload={date,type:readinessOnly?'Readiness only':type,workoutSource:readinessOnly?'Readiness only':workoutSource,readiness,sleep,energy,stress,backPain,nerve,anklePain,ankleStability,shoulder,dogWalk,notes,exercises:readinessOnly?[]:workoutExercises}; setSaveStatus('Saving to Notion…'); try{const res=await fetch('/api/workouts',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)}); const result=await res.json(); if(!res.ok)throw new Error(result.error||'Save failed'); setSaveStatus(`Saved to Notion. Session created with ${result.workoutExercisesCreated} exercises and ${result.setsCreated} sets.`); if(!readinessOnly)localStorage.removeItem(STORAGE_KEY)}catch(e){setSaveStatus(`Saved draft locally, but Notion save failed: ${e.message}`)}}
  function resetDraft(){setWorkoutExercises([]); setNotes(''); setSaveStatus('')}
  return <div className="app"><main className="shell"><header className="header"><div><p className="overline">Rehab Strength v2</p><h1>Notion Training Log</h1></div><button className="mini" onClick={loadExercises}>Sync library</button></header>
  {tab==='today'&&<section className="stack"><div className="panel"><div className="sectionTitle"><CalendarDays size={20}/><h2>Readiness</h2></div><label className="label">Date<input className="input" type="date" value={date} onChange={e=>setDate(e.target.value)}/></label></div><div className="readiness panel"><div className="row"><div><p className="muted">Today’s readiness</p><h2 className="big">{readiness>=18?'Green':readiness>=12?'Amber':'Red'}</h2><p className="muted">{readiness}/25</p></div><div className="bubble">{readiness>=18?<CheckCircle2/>:<AlertTriangle/>}</div></div><div className="bar"><div style={{width:`${(readiness/25)*100}%`}}/></div></div><div className="coach"><AlertTriangle size={20}/><p>{coachNote}</p></div><Slider label="Sleep quality" value={sleep} setValue={setSleep} lowGood={false}/><Slider label="Energy" value={energy} setValue={setEnergy} lowGood={false}/><Slider label="Stress" value={stress} setValue={setStress}/><Slider label="Back pain" value={backPain} setValue={setBackPain}/><Slider label="Left leg nerve/numbness" value={nerve} setValue={setNerve}/><Slider label="Left ankle pain" value={anklePain} setValue={setAnklePain}/><Slider label="Left ankle stability" value={ankleStability} setValue={setAnkleStability} lowGood={false}/><Slider label="Left shoulder sensation/pain" value={shoulder} setValue={setShoulder}/><Slider label="Dog walk minutes" value={dogWalk} setValue={setDogWalk} lowGood={false}/><div className="panel"><div className="sectionTitle"><Dumbbell size={20}/><h2>Choose workout</h2></div><div className="planGrid">{Object.entries(recommendedPlans).map(([key,plan])=><button key={key} className={selectedPlan===key?'active plan':'plan'} onClick={()=>applyRecommendedPlan(key)}>{plan.title}</button>)}</div><button className="secondary full" onClick={buildCustomWorkout}><Plus size={16}/> Build my own workout</button></div><textarea className="notes" placeholder="Session/readiness notes…" value={notes} onChange={e=>setNotes(e.target.value)}/><button className="secondary full" onClick={()=>saveWorkout(true)}><Save size={16}/> Save readiness only</button>{saveStatus&&<div className="saveStatus">{saveStatus}</div>}</section>}
  {tab==='workout'&&<section className="stack"><div className="panel"><div className="sectionTitle"><Dumbbell size={20}/><h2>{type}</h2></div><p className="muted">Source: {workoutSource} · {workoutExercises.length} exercises</p></div>{workoutExercises.map(ex=><div className="panel exerciseCard" key={ex.localId}><div className="row"><div><h3>{ex.name}</h3><p className="muted">{ex.status} · {ex.category}</p></div><button className="iconBtn" onClick={()=>removeExercise(ex.localId)}><Trash2 size={16}/></button></div>{ex.coachNote&&<p className="note">{ex.coachNote}</p>}<div className="miniGrid"><Field label="Target sets" value={ex.targetSets} setValue={v=>updateExercise(ex.localId,{targetSets:v})}/><label className="field"><span>Target reps</span><input value={ex.targetReps} onChange={e=>updateExercise(ex.localId,{targetReps:e.target.value})}/></label></div><div className="sets">{ex.sets.map((set,i)=><div className="setRow" key={i}><b>{i+1}</b><input placeholder="kg" inputMode="decimal" value={set.weight} onChange={e=>updateSet(ex.localId,i,{weight:e.target.value})}/><input placeholder="reps" inputMode="numeric" value={set.reps} onChange={e=>updateSet(ex.localId,i,{reps:e.target.value})}/><input placeholder="RPE" inputMode="decimal" value={set.rpe} onChange={e=>updateSet(ex.localId,i,{rpe:e.target.value})}/></div>)}</div><button className="ghost" onClick={()=>addSet(ex.localId)}><Plus size={16}/> Add set</button><div className="miniGrid"><Field label="Back" value={ex.backDuringExercise} setValue={v=>updateExercise(ex.localId,{backDuringExercise:v})}/><Field label="Nerve" value={ex.nerveDuringExercise} setValue={v=>updateExercise(ex.localId,{nerveDuringExercise:v})}/><Field label="Ankle" value={ex.ankleDuringExercise} setValue={v=>updateExercise(ex.localId,{ankleDuringExercise:v})}/><Field label="Shoulder" value={ex.shoulderDuringExercise} setValue={v=>updateExercise(ex.localId,{shoulderDuringExercise:v})}/></div><textarea className="notes small" placeholder="Exercise notes…" value={ex.notes} onChange={e=>updateExercise(ex.localId,{notes:e.target.value})}/></div>)}<button className="secondary full" onClick={()=>setTab('library')}><Plus size={16}/> Add exercise</button><button className="primary full" onClick={()=>saveWorkout(false)}><Save size={16}/> Save workout to Notion</button><button className="ghost full" onClick={resetDraft}><RotateCcw size={16}/> Clear draft exercises</button>{saveStatus&&<div className="saveStatus">{saveStatus}</div>}</section>}
  {tab==='library'&&<section className="stack"><div className="panel"><div className="sectionTitle"><Library size={20}/><h2>Exercise Library</h2></div><p className="muted">{exerciseStatus}</p><div className="search"><Search size={16}/><input placeholder="Search exercises…" value={query} onChange={e=>setQuery(e.target.value)}/></div><select className="input" value={categoryFilter} onChange={e=>setCategoryFilter(e.target.value)}>{categories.map(cat=><option key={cat}>{cat}</option>)}</select></div><div className="exerciseList">{filtered.map(exercise=><button key={exercise.id} className="libraryItem" onClick={()=>addExercise(exercise)}><div><b>{exercise.exercise}</b><p>{exercise.category} · {exercise.status}</p><small>{exercise.coachNote}</small></div><Plus size={18}/></button>)}</div><div className="panel"><div className="sectionTitle"><Plus size={20}/><h2>Create custom exercise</h2></div><input className="input" placeholder="Exercise name" value={custom.exercise} onChange={e=>setCustom({...custom,exercise:e.target.value})}/><input className="input" placeholder="Category" value={custom.category} onChange={e=>setCustom({...custom,category:e.target.value})}/><input className="input" placeholder="Equipment, comma-separated" value={custom.equipment} onChange={e=>setCustom({...custom,equipment:e.target.value})}/><input className="input" placeholder="Primary muscles, comma-separated" value={custom.primaryMuscles} onChange={e=>setCustom({...custom,primaryMuscles:e.target.value})}/><input className="input" placeholder="Risk flags, comma-separated" value={custom.riskFlags} onChange={e=>setCustom({...custom,riskFlags:e.target.value})}/><div className="miniGrid"><Field label="Default sets" value={custom.defaultSets} setValue={v=>setCustom({...custom,defaultSets:v})}/><label className="field"><span>Default reps</span><input value={custom.defaultReps} onChange={e=>setCustom({...custom,defaultReps:e.target.value})}/></label></div><textarea className="notes small" placeholder="Coach note" value={custom.coachNote} onChange={e=>setCustom({...custom,coachNote:e.target.value})}/><button className="primary full" onClick={createCustomExercise}><Plus size={16}/> Save custom exercise to Notion</button></div></section>}
  {tab==='rules'&&<section className="stack"><div className="panel"><div className="sectionTitle"><Activity size={20}/><h2>Rules</h2></div><ul><li>Green: train as planned, 2–3 reps in reserve.</li><li>Amber: reduce load 10–20% and avoid new exercises.</li><li>Red: rehab/cardio only.</li><li>Stop for sharp pain, worsening numbness, new weakness, foot drop feeling, ankle giving way, or shoulder instability.</li><li>New custom exercises are saved into Notion’s Exercise Library.</li><li>Each workout creates rows in Workout Sessions, Workout Exercises and Exercise Sets.</li></ul></div><div className="panel"><h2>Backend health check</h2><p className="muted">Open <code>/api/health</code> on your Vercel URL to confirm all Notion environment variables are configured.</p></div></section>}
  </main><nav className="bottomNav"><button className={tab==='today'?'active':''} onClick={()=>setTab('today')}>Today</button><button className={tab==='workout'?'active':''} onClick={()=>setTab('workout')}>Workout</button><button className={tab==='library'?'active':''} onClick={()=>setTab('library')}>Library</button><button className={tab==='rules'?'active':''} onClick={()=>setTab('rules')}>Rules</button></nav></div>
}
